Starting                	04.10. 19:49:11 Time taken: --:--:--:--
make trotter
Qubits set to  {0, 1, 2, 3}
Arguments where set as:
	sum: False
	pntsamples: 16
	pntsinglesamples: 100
	persamples: 100
	shots: 1024
	backend: FakeMelbourneV2
	cross: False
	onlyTomography: False
	setqubits: {0, 1, 2, 3}
	depths: [2, 4, 8, 16]
Namebase will be: False_16_100_100_1024_FakeMelbourneV2_False_False_{0, 1, 2, 3}_[2, 4, 8, 16]
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/localdisk/fabrice_remote_experiments/AutomatedPERTools/tutorial_notebooks/testrun/process_experiment_pickle.py", line 193, in make_transfer_matrix
    transfer_matrix = PTM(true_error.to_quantumchannel()).data
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/localdisk/fabrice_remote_experiments/AutomatedPERTools/.venv/lib/python3.11/site-packages/qiskit_aer/noise/errors/quantum_error.py", line 424, in to_quantumchannel
    ret = SuperOp(np.zeros([dim * dim, dim * dim]))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
Starting                	04.10. 19:49:11 Time taken: 00:00:00:01
Saving data             	04.10. 19:49:12 Time taken: --:--:--:--